version: '3.8'

services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: reyhan
      POSTGRES_PASSWORD: Reyhan456
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: test
      DATABASE_PASSWORD: Reyhan456
      APPLICATION_PORT: 8080
    depends_on:
      - postgres

  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    container_name: frontend
    ports:
      - "80:80"
    environment:
      APPLICATION_PORT: 80
      NGINX_ROOT_DOCUMENT: /var/www/html
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      BACKEND_CONTEXT_PATH: /
    depends_on:
      - backend

volumes:
  postgres_data:
